#!/bin/zsh

# Define the directory where the scripts are stored
if [ -z "$ZSH_CONFIG_DIR" ]; then
    echo "Error: ZSH_CONFIG_DIR is not set."
    exit 1
fi

SCRIPT_DIR="$ZSH_CONFIG_DIR/scripts"

# Check if the argument is provided
if [ -z "$1" ]; then
    echo "Usage: $0 <script_name> [args]"
    exit 1
fi

# Check if the specified script exists
SCRIPT="$SCRIPT_DIR/$1.sh"
"$SCRIPT" "${@:2}"